"""Initial database schema based on ERD

Revision ID: 8b8adad6597d
Revises: 
Create Date: 2025-05-24 07:32:28.917104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8adad6597d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_type')
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'version', name='uq_panel_version')
    )
    op.create_table('test_agg',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=256), nullable=False),
    sa.Column('last_status', sa.Enum('PASS', 'FAIL', 'IGNORED', 'SKIPPED', 'WARNING', name='teststatus'), nullable=True),
    sa.Column('last_started_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('fails', sa.Integer(), nullable=True),
    sa.Column('ignores', sa.Integer(), nullable=True),
    sa.Column('skips', sa.Integer(), nullable=True),
    sa.Column('flips', sa.Integer(), nullable=True),
    sa.Column('t1_transition_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('t2_fail_after_pass', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('t3_retry_success', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('t4_flaky_flag', sa.Boolean(), nullable=True),
    sa.Column('t5_weighted_instab', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_duration', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('median_duration', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'test_id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=256), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'IGNORED', 'SKIPPED', 'WARNING', name='teststatus'), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('started_ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_runs')
    op.drop_table('test_agg')
    op.drop_table('versions')
    op.drop_table('panels')
    # ### end Alembic commands ###
