"""Add class_name to test_agg

Revision ID: f89d058a36ea
Revises: 8b8adad6597d
Create Date: 2025-05-24 07:44:36.292155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89d058a36ea'
down_revision = '8b8adad6597d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_agg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_agg', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
