import os
import pandas as pd
from functools import lru_cache
from dashboard.config import Config

# --- File Paths ---
METRICS_CSV = os.path.join(Config.DATA_DIR, "metrics.csv")
HISTORY_PARQUET = os.path.join(Config.DATA_DIR, "forecast_history.parquet")
# Placeholders for files that will be generated by the daily cron job
SIGNALS_TODAY_PARQUET = os.path.join(Config.DATA_DIR, "signals_today.parquet")
EQUITY_CURVE_CSV = os.path.join(Config.DATA_DIR, "equity_curve.csv")


# --- Data Loading Functions ---

@lru_cache(maxsize=32)
def get_historical_signals():
    """Loads the complete history of signals from the parquet file."""
    if not os.path.exists(HISTORY_PARQUET):
        return pd.DataFrame()
    return pd.read_parquet(HISTORY_PARQUET)

@lru_cache(maxsize=32)
def get_metrics_history():
    """Loads the history of calculated metrics."""
    if not os.path.exists(METRICS_CSV):
        return pd.DataFrame()
    return pd.read_csv(METRICS_CSV)

def get_latest_metrics():
    """Returns the most recent row of metrics as a dictionary."""
    metrics_df = get_metrics_history()
    if metrics_df.empty:
        return {
            "sharpe_ratio_60d": 0,
            "coverage_pct": 0,
            "psi_confidence": 0,
            "date": "N/A"
        }
    return metrics_df.iloc[-1].to_dict()

# --- Placeholder Functions (to be implemented as cron jobs generate these files) ---

def get_todays_signals():
    """Loads the signals generated today."""
    if not os.path.exists(SIGNALS_TODAY_PARQUET):
        # Return a sample for development
        return pd.DataFrame([
            {'ticker': 'AAPL', 'horizon_days': 1, 'direction': 'Long', 'expected_return': 0.0075, 'weight': 0.025, 'confidence_sigma': 1.1},
            {'ticker': 'MSFT', 'horizon_days': 5, 'direction': 'Short', 'expected_return': -0.012, 'weight': 0.018, 'confidence_sigma': 0.9},
            {'ticker': 'CSPX.L', 'horizon_days': 20, 'direction': 'Long', 'expected_return': 0.025, 'weight': 0.03, 'confidence_sigma': 1.4},
        ])
    return pd.read_parquet(SIGNALS_TODAY_PARQUET)

@lru_cache(maxsize=4)
def get_equity_curve():
    """Loads the equity curve data."""
    if not os.path.exists(EQUITY_CURVE_CSV):
        # Return a sample for development
        dates = pd.to_datetime(pd.date_range(start="2023-01-01", periods=100))
        equity = 100 + (pd.Series(range(100)) * 0.5 + pd.Series(pd.np.random.randn(100)).cumsum())
        spy_equity = 100 + (pd.Series(range(100)) * 0.3 + pd.Series(pd.np.random.randn(100)).cumsum())
        return pd.DataFrame({
            "date": dates,
            "equity": equity,
            "spy_equity": spy_equity
        })
    return pd.read_csv(EQUITY_CURVE_CSV, parse_dates=['date'])
